### ISSUE TITLE
Parsing events error (panic EOF)

### ISSUE THREAD

**Issue by borispovod** [the729/lcs#1]
Hey there.

I'm using your library and trying to parse event output from execution of Move transaction.
During execution script emits `SentPaymentEvent`, that looks so:

```rust
struct SentPaymentEvent {
   // The amount of LibraCoin::T sent
   amount: u64,
        
   // The address that was paid
   payee: address,
}
```

And returns me next bytes in `WriteSet` (hex representation):
```
0a0000000000000002b9e56656c5b4695367100d8bcf34f309499acd62095d61f7676378006f803100000000
```

I'm trying to Unmarshall event with your LCS library, but getting panic error (EOF). It happens because of latest 4 bytes in the event. Not sure what these 4 bytes means, anyway it works only if i add another 4 bytes to then end of struct (int32 field) or ignore error.

You can see my code in [gist](https://gist.github.com/borispovod/83e7701f0b480cadea348524a00a2db0) (try to remove `Reserved` field to see panic).

**Comment by the729** [comment]
Hi, 

You might be using an old version of libra. According to the latest version, `SentPaymentEvent` has an extra member `metadata`. The 4 `00`s represent a zero-length byte array. And for security purposes, the lcs package only accept input with exactly correct length, when unmarshalling a struct. 

Rust code:
https://github.com/libra/libra/blob/ad4f45a1bef93be62895990262908f17ee348992/types/src/account_config.rs#L206

And Move code:
https://github.com/libra/libra/blob/ad4f45a1bef93be62895990262908f17ee348992/language/stdlib/modules/libra_account.mvir#L47

**Comment by the729** [comment]
Also, this package is a building block of `the729/go-libra` package, which is a full-fledged libra client library in golang. In case you are interested.

**Comment by borispovod** [comment]
I see, thank you for help! 
Closed.
